/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdbc.ihmMPT;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.NumberFormat;
import java.util.Locale;
import jdbc.observer.Observable;
import jdbc.observer.Observer;
import javax.swing.JFormattedTextField;
import jdbc.controler.AbstractControler;
import jdbc.observer.WhatChanged;

/**
 *
 * @author cflagollet
 */
public class VueReservation extends javax.swing.JFrame implements Observer {

  //L'instance de notre objet contrôleur
  private AbstractControler controler;
    
    /**
     * Creates new form IHMReservations
     */
    public VueReservation(AbstractControler controler) {
        
        //centrer la fenetre
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setSize( 1024, 768);
        setLocation(dim.width/2 - getWidth()/2, dim.height/2 - getHeight()/2);
        
        initComponents();
        this.controler= controler;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLblRepresentation = new javax.swing.JLabel();
        jCboAdherent = new javax.swing.JComboBox<>();
        jLblAdherent = new javax.swing.JLabel();
        jCboRepresentation = new javax.swing.JComboBox<>();
        jLblNbPersonnes = new javax.swing.JLabel();
        jFTxtNbPers =  new JFormattedTextField(NumberFormat.getIntegerInstance(Locale.FRANCE));
        jLblTotal = new javax.swing.JLabel();
        jTxtTotal = new javax.swing.JTextField();
        jBtnValider = new javax.swing.JButton();
        jBtnQuitter = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nouvelle réservation");
        setName("frmReservation"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridLayout(5, 2));

        jLblRepresentation.setText("Représentation :");
        jPanel1.add(jLblRepresentation);

        jCboAdherent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCboAdherent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboAdherentActionPerformed(evt);
            }
        });
        jPanel1.add(jCboAdherent);

        jLblAdherent.setText("Adhérent :");
        jPanel1.add(jLblAdherent);

        jCboRepresentation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jCboRepresentation);

        jLblNbPersonnes.setText("Nombre de personnes");
        jPanel1.add(jLblNbPersonnes);
        jPanel1.add(jFTxtNbPers);

        jLblTotal.setText("Total :");
        jPanel1.add(jLblTotal);

        jTxtTotal.setEditable(false);
        jTxtTotal.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jTxtTotal);

        jBtnValider.setText("Valider");
        jPanel1.add(jBtnValider);

        jBtnQuitter.setText("Quitter");
        jBtnQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnQuitterActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnQuitter);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 23, 410, 160));

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnQuitterActionPerformed
        
        //Fermeture de la base
      //  BdD.close();
        
        //on quitte
        System.exit(0);
    }//GEN-LAST:event_jBtnQuitterActionPerformed

    private void jCboAdherentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboAdherentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboAdherentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnQuitter;
    private javax.swing.JButton jBtnValider;
    private javax.swing.JComboBox<String> jCboAdherent;
    private javax.swing.JComboBox<String> jCboRepresentation;
    private javax.swing.JFormattedTextField jFTxtNbPers;
    private javax.swing.JLabel jLblAdherent;
    private javax.swing.JLabel jLblNbPersonnes;
    private javax.swing.JLabel jLblRepresentation;
    private javax.swing.JLabel jLblTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTxtTotal;
    // End of variables declaration//GEN-END:variables
 
    
    @Override
    public void update(WhatChanged wc) {
        
          switch (wc.mess) {
              case MSG_INIT : this.jFTxtNbPers.setText(String.valueOf((Integer)wc.O1));
                                  break;
              default           : break;

          }

                    // Modifier l’affichag
    }


}
