/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdbc.ihmMPT;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.NumberFormat;
import java.util.LinkedHashMap;
import java.util.Locale;
import jdbc.observer.Observable;
import jdbc.observer.Observer;
import javax.swing.JFormattedTextField;
import jdbc.controler.AbstractControler;
import jdbc.metier.Adherent;
import jdbc.metier.Representation;
import jdbc.modele.AbstractModel;
import jdbc.observer.WhatChanged;

/**
 *
 * @author cflagollet
 */
public class VueReservation extends javax.swing.JFrame implements Observer {

  //L'instance de notre objet contrôleur
  private AbstractControler controler;
  
    /**
     * Creates new form IHMReservations
     */
    public VueReservation(AbstractControler controler, AbstractModel model) {
        
        //centrer la fenetre
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setSize( 1024, 768);
        setLocation(dim.width/2 - getWidth()/2, dim.height/2 - getHeight()/2);
        
        initComponents();
        this.controler= controler;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLblAdherent = new javax.swing.JLabel();
        jCboAdherent = new javax.swing.JComboBox<>();
        jLblRepresentation = new javax.swing.JLabel();
        jCboRepresentation = new javax.swing.JComboBox<>();
        jLblNbPersonnes = new javax.swing.JLabel();
        jTxtNbPers = new javax.swing.JTextField();
        jLblTotal = new javax.swing.JLabel();
        jTxtTotal = new javax.swing.JTextField();
        jBtnValider = new javax.swing.JButton();
        jBtnQuitter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nouvelle réservation");
        setName("frmReservation"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridLayout(5, 1));

        jLblAdherent.setText("Adhérent :");
        jPanel1.add(jLblAdherent);
        validate();

        jPanel1.add(jCboAdherent);
        validate();

        jLblRepresentation.setText("Représentation :");
        jPanel1.add(jLblRepresentation);
        validate();

        jPanel1.add(jCboRepresentation);
        validate();

        jLblNbPersonnes.setText("Nombre de personnes");
        jPanel1.add(jLblNbPersonnes);
        validate();

        jTxtNbPers.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtNbPersFocusLost(evt);
            }
        });
        jTxtNbPers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNbPersActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtNbPers);

        jLblTotal.setText("Total :");
        jPanel1.add(jLblTotal);

        jTxtTotal.setEditable(false);
        jTxtTotal.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jTxtTotal);

        jBtnValider.setText("Valider");
        jBtnValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnValiderActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnValider);

        jBtnQuitter.setText("Quitter");
        jBtnQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnQuitterActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnQuitter);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 23, 450, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnQuitterActionPerformed
        
        //Fermeture de la base
        controler.closeDB();        
        //on quitte
        System.exit(0);
    }//GEN-LAST:event_jBtnQuitterActionPerformed

    private void jTxtNbPersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNbPersActionPerformed
        controler.setNbPersonnes(jTxtNbPers.getText().trim());
    }//GEN-LAST:event_jTxtNbPersActionPerformed

    private void jTxtNbPersFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtNbPersFocusLost
        controler.setNbPersonnes(jTxtNbPers.getText().trim());
    }//GEN-LAST:event_jTxtNbPersFocusLost

    private void jBtnValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnValiderActionPerformed
        controler.save();
    }//GEN-LAST:event_jBtnValiderActionPerformed

    private void jCboRepresentationActionPerformed(java.awt.event.ActionEvent evt) {                                             
        controler.setRepresentation(jCboRepresentation.getSelectedIndex());    
    }   
    
    private void jCboAdherentActionPerformed(java.awt.event.ActionEvent evt) {                                             
        controler.setAdherent(jCboAdherent.getSelectedIndex());    
    }   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnQuitter;
    private javax.swing.JButton jBtnValider;
    private javax.swing.JComboBox<String> jCboAdherent;
    private javax.swing.JComboBox<String> jCboRepresentation;
    private javax.swing.JLabel jLblAdherent;
    private javax.swing.JLabel jLblNbPersonnes;
    private javax.swing.JLabel jLblRepresentation;
    private javax.swing.JLabel jLblTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtNbPers;
    private javax.swing.JTextField jTxtTotal;
    // End of variables declaration//GEN-END:variables
 
    
    @Override
    public void update(WhatChanged wc) {
        
          switch (wc.mess) {
              case MSG_INIT : 
                                this.jTxtNbPers.setText(String.valueOf((Integer)wc.O1));
                                LinkedHashMap<Integer,Adherent> hash =(LinkedHashMap<Integer,Adherent>) wc.O2;
                                jCboAdherent.removeAllItems();
                                for (Adherent a : (hash.values())) {
                                    jCboAdherent.addItem(a.getNomAdhrent()+" "+a.getPrenomAdherent());
                                }  
                                jCboAdherent.setSelectedIndex(-1);
                                jCboRepresentation.removeAll();
                                LinkedHashMap<Integer,Representation> hashR =(LinkedHashMap<Integer,Representation>) wc.O3;
                                for (Representation r : (hashR.values())) {
                                    jCboRepresentation.addItem(r.getDateRepresentation()+" "+r.getNomSpectacle());
                                }  
                                jCboRepresentation.setSelectedIndex(-1);
                                jCboRepresentation.addActionListener(new java.awt.event.ActionListener() {
                                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                              jCboRepresentationActionPerformed(evt);
                                        }
                                });
                               jCboAdherent.addActionListener(new java.awt.event.ActionListener() {
                                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            jCboAdherentActionPerformed(evt);
                                        }
                                });
                                jTxtNbPers.setText(String.valueOf((int)wc.O4));
                                jTxtTotal.setText(String.valueOf((double)wc.O5));
                                break;
              case MSG_TOTAL : 
                                jTxtTotal.setText(String.valueOf((double)wc.O1));
                                break;
              case MSG_NBPERS :
                                jTxtNbPers.setText(String.valueOf((int)wc.O1));
                                jTxtTotal.setText(String.valueOf((double)wc.O2));
                                break;
                
              default       : break;

          }

                    // Modifier l’affichag
    }


}
